import type { Address, Category, Order, Product, Review } from '@/features/marketplace/types';

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const CATEGORIES: Category[] = [
  {
    slug: 'eletronicos',
    name: 'Eletrônicos',
    description: 'Áudio, celulares e acessórios com entrega rápida.',
  },
  {
    slug: 'casa',
    name: 'Casa',
    description: 'Peças para deixar a casa mais prática e acolhedora.',
  },
  {
    slug: 'moda',
    name: 'Moda',
    description: 'Roupas, calçados e bolsas para o dia a dia.',
  },
  {
    slug: 'beleza',
    name: 'Beleza',
    description: 'Cuidados pessoais para o dia a dia.',
  },
  {
    slug: 'esportes',
    name: 'Esportes',
    description: 'Equipamentos leves para treinar em casa ou ao ar livre.',
  },
  {
    slug: 'mercado',
    name: 'Mercado',
    description: 'Despensa, café e itens do consumo do mês.',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p-fone',
    slug: 'fone-sem-fio-norte',
    name: 'Fone sem fio com estojo',
    summary: 'Som equilibrado, estojo com 24 h e encaixe estável.',
    description:
      'Fone intra-auricular com drivers de 10 mm, microfone para chamadas e estojo que recarrega por USB-C. A vedação em silicone vem em três tamanhos.\n\nO estojo completa até 24 h de uso. A conexão Bluetooth 5.3 serve para celular, tablet ou computador, e a garantia de loja é de 90 dias.',
    price: 34_990,
    compareAtPrice: 42_990,
    categorySlug: 'eletronicos',
    images: [
      img('photo-1505740420928-5e560c06d30e'),
      img('photo-1484704849700-f032a568e944'),
      img('photo-1546435770-a3e426bf472b'),
      img('photo-1583394838336-acd977736f90'),
    ],
    variantLabel: 'Cor',
    variants: [
      { id: 'preto', label: 'Preto', swatch: '#1c1c1c' },
      { id: 'branco', label: 'Branco', swatch: '#f4f4f5' },
      { id: 'azul', label: 'Azul', swatch: '#3d5a80' },
    ],
    rating: 4.7,
    reviewCount: 186,
    stock: 14,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'É sem fio', value: 'Sim' },
      { label: 'Com microfone', value: 'Sim' },
      { label: 'Duração da bateria', value: '24 h com o estojo' },
      { label: 'Conexão', value: 'Bluetooth 5.3' },
      { label: 'Recarga', value: 'USB-C' },
      { label: 'Garantia', value: '90 dias' },
    ],
  },
  {
    id: 'p-tenis',
    slug: 'tenis-corrida-lima',
    name: 'Tênis de corrida leve',
    summary: 'Cabedal respirável e amortecimento para uso diário.',
    description:
      'Tênis com solado em borracha contínua e entressola macia. Indicado para caminhada e corrida leve em asfalto. Numeração informada no anúncio da loja.',
    price: 29_990,
    compareAtPrice: 39_990,
    categorySlug: 'moda',
    images: [
      img('photo-1542291026-7eec264c27ff'),
      img('photo-1460353581641-37baddab0fa2'),
      img('photo-1549298916-b41d501d3772'),
    ],
    variantLabel: 'Numeração',
    variants: [
      { id: '38', label: '38' },
      { id: '39', label: '39' },
      { id: '40', label: '40' },
      { id: '41', label: '41' },
      { id: '42', label: '42' },
    ],
    rating: 4.8,
    reviewCount: 94,
    stock: 8,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Uso', value: 'Corrida leve' },
      { label: 'Fechamento', value: 'Cadarço' },
      { label: 'Solado', value: 'Borracha' },
    ],
  },
  {
    id: 'p-relogio',
    slug: 'relogio-analogico-azul',
    name: 'Relógio analógico de aço',
    summary: 'Caixa fina, pulseira de malha e mostrador fosco.',
    description:
      'Relógio de pulso com caixa de 40 mm, vidro mineral e resistência a respingos. A pulseira de malha fecha por fecho deslizante.',
    price: 18_990,
    compareAtPrice: null,
    categorySlug: 'moda',
    images: [
      img('photo-1523275335684-37898b6baf30'),
      img('photo-1524805444758-089113d48a6d'),
      img('photo-1522312346375-d1a52e2b99b3'),
    ],
    variantLabel: 'Cor',
    variants: [
      { id: 'prata', label: 'Prata', swatch: '#c5c7cb' },
      { id: 'preto', label: 'Preto', swatch: '#1c1c1c' },
      { id: 'azul', label: 'Azul', swatch: '#1e3a5f' },
    ],
    rating: 4.5,
    reviewCount: 41,
    stock: 6,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Caixa', value: '40 mm' },
      { label: 'Pulseira', value: 'Aço' },
      { label: 'Resistência', value: 'Respingos' },
    ],
  },
  {
    id: 'p-mochila',
    slug: 'mochila-urbana-usada',
    name: 'Mochila urbana 18 L',
    summary: 'Usada em ótimo estado, com compartimento para notebook.',
    description:
      'Mochila de lona com porta notebook até 15 polegadas, bolso frontal e alças acolchoadas. Peça única, fotografada do item à venda.',
    price: 15_990,
    compareAtPrice: null,
    categorySlug: 'moda',
    images: [
      img('photo-1553062407-98eeb64c6a62'),
      img('photo-1622560480605-d83c853bc5c3'),
      img('photo-1474376962954-d8a681cc53b2'),
    ],
    rating: 4.4,
    reviewCount: 12,
    stock: 1,
    condition: 'usado',
    freeShipping: false,
    specs: [
      { label: 'Capacidade', value: '18 litros' },
      { label: 'Estado', value: 'Seminovo' },
      { label: 'Notebook', value: 'Até 15"' },
    ],
  },
  {
    id: 'p-luminaria',
    slug: 'luminaria-mesa-norte',
    name: 'Luminária de mesa articulada',
    summary: 'Luz quente, braço flexível e base estável.',
    description:
      'Luminária para cabeceira ou escrivaninha, com dimerização em três níveis e cabo de 1,5 m. A cúpula direciona a luz para baixo.',
    price: 24_990,
    compareAtPrice: 29_990,
    categorySlug: 'casa',
    images: [
      img('photo-1507473885765-e6ed057f782c'),
      img('photo-1513506003901-1e6a229e2d15'),
      img('photo-1540932239986-30128078f3c5'),
    ],
    variantLabel: 'Cor',
    variants: [
      { id: 'preto', label: 'Preto', swatch: '#1c1c1c' },
      { id: 'branco', label: 'Branco', swatch: '#f5f5f4' },
    ],
    rating: 4.9,
    reviewCount: 63,
    stock: 5,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Luz', value: 'Quente, 3 níveis' },
      { label: 'Altura', value: '42 cm' },
      { label: 'Cabo', value: '1,5 m' },
    ],
  },
  {
    id: 'p-cafe',
    slug: 'cafe-torrado-serra',
    name: 'Café torrado 500 g',
    summary: 'Grãos torrados médios, moagem para coador.',
    description:
      'Pacote de 500 g com torra média, notas de chocolate e baixa acidez. Moagem indicada para coador de papel. Validade impressa no lote.',
    price: 2_890,
    compareAtPrice: null,
    categorySlug: 'mercado',
    images: [
      img('photo-1495474472287-4d71bcdd2085'),
      img('photo-1447933601403-0c6688de566e'),
      img('photo-1498804103079-a6351b050096'),
    ],
    rating: 4.6,
    reviewCount: 220,
    stock: 40,
    condition: 'novo',
    freeShipping: false,
    specs: [
      { label: 'Peso', value: '500 g' },
      { label: 'Torra', value: 'Média' },
      { label: 'Moagem', value: 'Coador' },
    ],
  },
  {
    id: 'p-planta',
    slug: 'jiboia-vaso-ceramica',
    name: 'Jiboia em vaso de cerâmica',
    summary: 'Planta fácil de cuidar, vaso incluso.',
    description:
      'Epipremnum em vaso de cerâmica de 15 cm. Gosta de luz indireta e rega quando o substrato seca. Item esgotado neste lote.',
    price: 7_990,
    compareAtPrice: null,
    categorySlug: 'casa',
    images: [
      img('photo-1485955900006-10f4d324d411'),
      img('photo-1463320726281-696a485928c7'),
      img('photo-1459411552884-841db9b3cc2a'),
    ],
    rating: 4.8,
    reviewCount: 33,
    stock: 0,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Vaso', value: '15 cm' },
      { label: 'Luz', value: 'Indireta' },
      { label: 'Porte', value: 'Pequeno' },
    ],
  },
  {
    id: 'p-celular',
    slug: 'celular-128-azul',
    name: 'Celular 128 GB, tela 6,5"',
    summary: 'Aparelho novo de vitrine, com carregador.',
    description:
      'Smartphone com 128 GB, tela de 6,5 polegadas e câmera dupla. Acompanha cabo, carregador e película aplicada. Garantia de loja de 6 meses.',
    price: 189_900,
    compareAtPrice: null,
    categorySlug: 'eletronicos',
    images: [
      img('photo-1511707171634-5f897ff02aa9'),
      img('photo-1510557880182-3d4d3cba35a5'),
      img('photo-1592899677977-9c10ca588bbd'),
    ],
    variantLabel: 'Cor',
    variants: [
      { id: 'azul', label: 'Azul', swatch: '#1e3a5f' },
      { id: 'preto', label: 'Preto', swatch: '#1c1c1c' },
      { id: 'branco', label: 'Branco', swatch: '#f4f4f5' },
    ],
    rating: 4.6,
    reviewCount: 58,
    stock: 3,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Armazenamento', value: '128 GB' },
      { label: 'Tela', value: '6,5"' },
      { label: 'Garantia', value: '6 meses' },
    ],
  },
  {
    id: 'p-serum',
    slug: 'serum-vitamina-c',
    name: 'Sérum vitamina C 30 ml',
    summary: 'Textura leve para uso de manhã, antes do protetor.',
    description:
      'Sérum facial com vitamina C estabilizada, frasco âmbar de 30 ml e conta-gotas. Aplicar 3 gotas no rosto limpo. Uso diurno.',
    price: 8_990,
    compareAtPrice: null,
    categorySlug: 'beleza',
    images: [
      img('photo-1556228720-195a672e8a03'),
      img('photo-1571781926291-c477ebfd024b'),
      img('photo-1608248543803-ba4f8c70ae0b'),
    ],
    rating: 4.7,
    reviewCount: 77,
    stock: 18,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Volume', value: '30 ml' },
      { label: 'Uso', value: 'Diurno' },
      { label: 'Tipo de pele', value: 'Todas' },
    ],
  },
  {
    id: 'p-tapete',
    slug: 'tapete-yoga-5mm',
    name: 'Tapete de yoga 5 mm',
    summary: 'Antiderrapante dos dois lados e alça de transporte.',
    description:
      'Tapete de 183 × 61 cm, espessura de 5 mm, com textura antiderrapante. Acompanha alça. Pode ser lavado com pano úmido.',
    price: 12_990,
    compareAtPrice: null,
    categorySlug: 'esportes',
    images: [
      img('photo-1544367567-0f2fcb009e0b'),
      img('photo-1601925260368-ae2f83cf8b7f'),
      img('photo-1545205597-3d9d02c29597'),
    ],
    variantLabel: 'Cor',
    variants: [
      { id: 'roxo', label: 'Roxo', swatch: '#6d28d9' },
      { id: 'preto', label: 'Preto', swatch: '#1c1c1c' },
      { id: 'azul', label: 'Azul', swatch: '#1d4ed8' },
    ],
    rating: 4.5,
    reviewCount: 29,
    stock: 11,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Medida', value: '183 × 61 cm' },
      { label: 'Espessura', value: '5 mm' },
      { label: 'Material', value: 'TPE' },
    ],
  },
  {
    id: 'p-panelas',
    slug: 'jogo-panelas-3-pecas',
    name: 'Jogo de panelas 3 peças',
    summary: 'Alumínio com antiaderente e tampas de vidro.',
    description:
      'Conjunto com caçarola e duas panelas, cabos frios ao toque e tampas de vidro. Pode ir à lava-louças, sem as tampas. Fogão a gás ou elétrico.',
    price: 21_990,
    compareAtPrice: null,
    categorySlug: 'casa',
    images: [
      img('photo-1556909114-f6e7ad7d3136'),
      img('photo-1590794056226-79ef3a8147e1'),
      img('photo-1556911220-bff31c812dba'),
    ],
    rating: 4.4,
    reviewCount: 51,
    stock: 7,
    condition: 'novo',
    freeShipping: true,
    specs: [
      { label: 'Peças', value: '3' },
      { label: 'Revestimento', value: 'Antiaderente' },
      { label: 'Fogão', value: 'Gás e elétrico' },
    ],
  },
  {
    id: 'p-livro',
    slug: 'caderno-receitas-capa-dura',
    name: 'Caderno de receitas capa dura',
    summary: '120 páginas em branco, marcador de tecido.',
    description:
      'Caderno costurado com capa dura e papel pólen 90 g. Serve para receitas, listas e anotações de feira. Não é um livro impresso.',
    price: 4_590,
    compareAtPrice: null,
    categorySlug: 'mercado',
    images: [
      img('photo-1512820790803-83ca734da794'),
      img('photo-1544947950-fa07a98d237f'),
      img('photo-1457369804613-52c61a468e7d'),
    ],
    rating: 4.9,
    reviewCount: 18,
    stock: 22,
    condition: 'novo',
    freeShipping: false,
    specs: [
      { label: 'Páginas', value: '120' },
      { label: 'Papel', value: 'Pólen 90 g' },
      { label: 'Capa', value: 'Dura' },
    ],
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    productId: 'p-fone',
    author: 'Marina A.',
    rating: 5,
    comment:
      'Encaixa bem e a chamada fica nítida na rua. O estojo é pequeno o bastante para o bolso.',
    createdAt: '2026-08-02T12:00:00.000Z',
  },
  {
    id: 'r2',
    productId: 'p-fone',
    author: 'Pedro L.',
    rating: 4,
    comment: 'Som bom para o preço. Os graves não estouram, mas o app de equalização não existe.',
    createdAt: '2026-07-18T12:00:00.000Z',
  },
  {
    id: 'r3',
    productId: 'p-tenis',
    author: 'Lívia M.',
    rating: 5,
    comment: 'Usei a semana inteira no caminho do trabalho. Não marcou o calcanhar.',
    createdAt: '2026-09-01T12:00:00.000Z',
  },
  {
    id: 'r4',
    productId: 'p-cafe',
    author: 'Rafael S.',
    rating: 5,
    comment: 'Torra uniforme. Rendeu um mês no coador da casa, duas xícaras por dia.',
    createdAt: '2026-09-20T12:00:00.000Z',
  },
  {
    id: 'r5',
    productId: 'p-luminaria',
    author: 'Helena C.',
    rating: 5,
    comment: 'A luz mais baixa serve para leitura. O braço segura a posição.',
    createdAt: '2026-06-11T12:00:00.000Z',
  },
];

export const DEMO_ADDRESS: Address = {
  id: 'addr-casa',
  label: 'Casa',
  recipient: 'Cliente',
  phone: '(41) 98888-1020',
  zip: '80010-000',
  street: 'Rua XV de Novembro',
  number: '120',
  complement: 'Apto 42',
  district: 'Centro',
  city: 'Curitiba',
  state: 'PR',
};

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-demo-1',
    code: 'GM-18420',
    createdAt: '2026-09-28T15:10:00.000Z',
    status: 'enviado',
    demo: true,
    contactName: 'Cliente',
    contactEmail: 'cliente@gescom.app',
    address: DEMO_ADDRESS,
    paymentMethod: 'pix',
    items: [
      {
        productId: 'p-luminaria',
        name: 'Luminária de mesa articulada',
        image: PRODUCTS[4]?.images[0] ?? '',
        price: 24_990,
        quantity: 1,
      },
    ],
    subtotal: 24_990,
    shipping: 0,
    total: 24_990,
  },
  {
    id: 'ord-demo-2',
    code: 'GM-17902',
    createdAt: '2026-08-14T11:00:00.000Z',
    status: 'entregue',
    demo: true,
    contactName: 'Cliente',
    contactEmail: 'cliente@gescom.app',
    address: DEMO_ADDRESS,
    paymentMethod: 'credito',
    items: [
      {
        productId: 'p-cafe',
        name: 'Café torrado 500 g',
        image: PRODUCTS[5]?.images[0] ?? '',
        price: 2_890,
        quantity: 2,
      },
    ],
    subtotal: 5_780,
    shipping: 1_990,
    total: 7_770,
  },
];

export const UF_OPTIONS = [
  'AC',
  'AL',
  'AP',
  'AM',
  'BA',
  'CE',
  'DF',
  'ES',
  'GO',
  'MA',
  'MT',
  'MS',
  'MG',
  'PA',
  'PB',
  'PR',
  'PE',
  'PI',
  'RJ',
  'RN',
  'RS',
  'RO',
  'RR',
  'SC',
  'SP',
  'SE',
  'TO',
] as const;
